name: deploy-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check prisma has changes
        uses: dorny/paths-filter@v3
        id: paths-filter
        with:
          filters: |
            prisma: ["prisma/**"]

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host weather-robe
            HostName $EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Workspace
        run: |
          ssh weather-robe 'sudo mkdir -p /opt/app'
          ssh weather-robe 'sudo chown ubuntu:ubuntu /opt/app'
          scp -r ./[!.]* weather-robe:/opt/app

      - name: Install dependencies
        run: |
          ssh weather-robe 'cd /opt/app; pnpm install'
          ssh weather-robe 'cd /opt/app; pnpm exec prisma generate'

      - name: Apply prisma migrations
        if: steps.paths-filter.outputs.prisma == 'true'
        run: |
          ssh weather-robe 'cd /opt/app; pnpm exec prisma migrate deploy'

      - name: Copy systemd service file
        run: |
          ssh weather-robe '
            echo "[Unit]
            Description=MJU RATS Project
            After=network.target

            [Service]
            User=ubuntu
            WorkingDirectory=/opt/app
            ExecStart=/usr/local/bin/pnpm start
            Restart=always
            Environment=PATH=/usr/local/bin:/usr/bin:/bin

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service
          '

      - name: Enable systemd service
        run: |
          ssh weather-robe 'sudo systemctl daemon-reload'
          ssh weather-robe 'sudo systemctl enable app'

      - name: Restart systemd service
        run: |
          ssh weather-robe 'sudo systemctl restart app'
